# Generated by Django 4.2.3 on 2023-07-12 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainschedule",
            name="name",
            field=models.CharField(
                help_text="Name of the train line (1 to 4 alphanumeric characters)",
                max_length=4,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name should contain 1 to 4 alphanumeric characters.",
                        regex="^[a-zA-Z0-9]{1,4}$",
                    )
                ],
            ),
        ),
    ]
